### ISSUE TITLE
How to parse streamresult in   List<DateTimeRange> convertStreamResultFirebase(

### ISSUE THREAD

**Issue by godopetza** [radikris/booking_calendar#16]
Im trying to pasrse the streamresult in   List<DateTimeRange> convertStreamResultFirebase(

How can I do that?
![image](https://user-images.githubusercontent.com/83901314/183775694-cb6b0da5-55d2-4be6-b6ae-1fdc175c5edd.png)

**Comment by radikris** [comment]
so the _streamResult_ in the parameter you will got it from my widget:

it is dynamic, because it will store the type you passed to the widget through the _getBookingStream_

In the implementation of my widget it looks like this:
` StreamBuilder<dynamic>(
                    stream: widget.getBookingStream(
                        start: startOfDay, end: endOfDay),
                    builder: (context, snapshot) {
                      if (snapshot.hasError) {
                        return widget.errorWidget ??
                            Center(
                              child: Text(snapshot.error.toString()),
                            );
                      }

                      if (!snapshot.hasData) {
                        return widget.loadingWidget ??
                            const Center(child: CircularProgressIndicator());
                      }

                      ///this snapshot should be converted to List<DateTimeRange>
                      final data = snapshot.requireData; **//THIS IS THE MOST IMPORTANT LINE**
                      controller.generateBookedSlots(
                          widget.convertStreamResultToDateTimeRanges(
                              streamResult: data));`
                              
                              
So the final data=snapshot.requireData will be the fetched data which you store in your firebase project, and this will be passed to the convertStream function, which you will receive on your end.

Probably, this _streamResult_ will be a list of object, but for firebase specific, it is a queryresult, in my case:
![image](https://user-images.githubusercontent.com/55052220/183843363-f46b1914-2592-4c4f-a860-ad1356b3a525.png)

But it depends on how you store your data in firebase.
so your data is with firebase a QueryResult, but if you did not use withConverter method like I did in the example you also need to deserialize the data, because by default it is a map:

` List<DateTimeRange> converted = []
      for (var i = 0; i < data.size; i++) {
        final item = data.docs[i].data();
        converted.add(DateTimeRange(start: (item.bookingStart!), end: (item.bookingEnd!)));
      }
  return converted;`

**Comment by godopetza** [comment]
Accoding to the firebase example, what is the ApiRepository?
![image](https://user-images.githubusercontent.com/83901314/183928861-a4e12621-02c7-4b38-92f7-0232b5ff616a.png)
