### ISSUE TITLE
Table Calendar Days issue

### ISSUE THREAD

**Issue by JohnnyCasares** [radikris/booking_calendar#18]
When I use a tablet, the days get cropped.

![flutter_01](https://user-images.githubusercontent.com/88862676/186740157-3d2b6a94-03bd-4fd9-82ad-5727cdce951b.png)

**Comment by radikris** [comment]
That part of the UI is an outer package, tablecalendar. I am not sure this issue is 100% related to my code.
If you could check out the same layout with the original package, I could add some trick to avoid this cropping with hardcoded height or expanded something like that, and will provie additional parameters on the BookingCalendar interface if neccessary, but currently this is not highpriority

**Comment by JohnnyCasares** [comment]
yes ofc
